# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hallon}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kim Burgestrand"]
  s.date = %q{2010-11-25}
  s.description = ''
  s.email = %q{kim@burgestrand.se}
  s.extensions = ["ext/extconf.rb"]
  s.extra_rdoc_files = [
    "ext/hallon.c"
  ]
  s.files = [
    "lib/hallon.rb"
  ]
  s.homepage = %q{http://github.com/Burgestrand/Hallon}
  s.licenses = ["GNU AGPL"]
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Delicious Ruby bindings for libspotify}
  s.test_files = [
    "spec/hallon_spec.rb",
    "spec/link_spec.rb",
    "spec/playlist_container_spec.rb",
    "spec/playlist_spec.rb",
    "spec/session_spec.rb",
    "spec/track_spec.rb",
    "spec/user_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2"])
    else
      s.add_dependency(%q<rspec>, ["~> 2"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2"])
  end
end

